### ISSUE TITLE
Add a face for the code-block background

### ISSUE THREAD

**Issue by Fuco1** [Fuco1/sphinx-mode#2]

**Comment by wbolster** [comment]
is there a reason you have this in the code at all?

```elisp
(add-face-text-property
 block-highlight-start block-end
 '(:inherit fixed-pitch :background "#232a2b") 'append)
```

in my case it gives ugly dark backgrounds on my (light) theme.

would this be solved by using a dedicated font face?

**Comment by Fuco1** [comment]
Yes, it should have its own face and probably inherit from something reasonable.  The value provided is what "works for me", heh

**Comment by wbolster** [comment]
sure, pls assign this ticket to me.
