### ISSUE TITLE
sphinx-mode does not depend on f on melpa

### ISSUE THREAD

**Issue by D4N** [Fuco1/sphinx-mode#8]
Somehow `sphinx-mode` does not depend on `f` on melpa, although appears to be included in the [Cask](https://github.com/Fuco1/sphinx-mode/blob/master/Cask) file. However it also includes `dash` as a dependency, which is also not visible on [melpa](https://melpa.org/#/sphinx-mode).

This currently results in an error when sphinx-mode is started.

It is however easy to work around that: just install `f` and `dash` manually.

**Comment by Fuco1** [comment]
Yea because the Cask file is ignored by melpa.  The markup needs to be in the file's package headers.

**Comment by D4N** [comment]
The dependencies are still not listed on melpa. I guess that the problem is, that `Package-Requires` should be maybe spelled with a capital `R`? (21c047c636560391d02314ada2d188677c311f6c adds the line with a lowercase `r`)

**Comment by Fuco1** [comment]
It takes a while for melpa to rebuild the package. It is probably still serving the old version.

**Comment by Fuco1** [comment]
We actually have a .pkg file, that should probably be deleted alltogether.  This is why it's not working on MELPA.

I'll play with this when I get home, I don't wont to break it further.

Thanks for getting back to me!

**Comment by D4N** [comment]
No problem, thanks for creating the package & responding so quickly to the issue!

**Comment by Fuco1** [comment]
It's fixed now https://melpa.org/#/sphinx-mode they are listed as dependencies.

**Comment by D4N** [comment]
Thanks a lot!
